version: '3.4'

x-template:
  php-common: &php-common
    command: /bin/bash -c "a2enmod rewrite && /usr/local/bin/apache2-foreground"
    volumes:
      - ./wwwroot:/var/www/html

services:
  tester:
    build: .
    volumes:
      - ./test:/app/test
    environment:
      - PHP_HOST=docker
      - PHP=${PHP:-}
    depends_on:
      - php-54
      - php-55
      - php-56
      - php-70
      - php-71
      - php-72
      - php-73
      - php-74
      - php-80
      - php-81
  php-54:
    image: php:5.4-apache
    <<: *php-common
    ports:
      - 10540:80
  php-55:
    image: php:5.5-apache
    <<: *php-common
    ports:
      - 10550:80
  php-56:
    image: php:5.6-apache
    <<: *php-common
    ports:
      - 10560:80
  php-70:
    image: php:7.0-apache
    <<: *php-common
    ports:
      - 10700:80
  php-71:
    image: php:7.1-apache
    <<: *php-common
    ports:
      - 10710:80
  php-72:
    image: php:7.2-apache
    <<: *php-common
    ports:
      - 10720:80
  php-73:
    image: php:7.3-apache
    <<: *php-common
    ports:
      - 10730:80
  php-74:
    image: php:7.4-apache
    <<: *php-common
    ports:
      - 10740:80
  php-80:
    image: php:8.0-apache
    <<: *php-common
    ports:
      - 10800:80
  php-81:
    image: php:8.1-apache
    <<: *php-common
    ports:
      - 10810:80
