name: CI/CD
on: ["push", "pull_request"]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      phpVersions: ${{ steps.read-versions.outputs.phpVersions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Read PHP versions
        id: read-versions
        run: |
          if [ ! -f .php-versions ]; then
            echo "Error: .php-versions file is required but not found"
            exit 1
          fi
          # Read versions from file, excluding comments and empty lines
          versions=$(grep -v '^#' .php-versions | grep -v '^$' | jq -R . | jq -s .)
          echo "phpVersions=$versions" >> $GITHUB_OUTPUT

  test:
    name: Test PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        php-version: ${{ fromJson(needs.setup.outputs.phpVersions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        env:
          PHP_VERSION: ${{ matrix.php-version }}
        run: go test -v ./...

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/tags/v' )
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Variables
        id: variables
        run: |
          echo "vtag=${GITHUB_REF##refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get tag message
        id: tag_message
        run: |
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${GITHUB_REF##refs/tags/})
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Build the package to release
        run: |
          VERSION="${GITHUB_REF#refs/tags/}" make build
      - name: Create a new release
        id: createNewRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.variables.outputs.vtag }}
          release_name: Release ${{ steps.variables.outputs.vtag }}
          body: ${{ steps.tag_message.outputs.message }}
          draft: false
          prerelease: false
      - name: Upload release package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createNewRelease.outputs.upload_url }}
          asset_path: ./built/phpwebp-concept-${{ steps.variables.outputs.vtag }}.zip
          asset_name: phpwebp-concept-${{ steps.variables.outputs.vtag }}.zip
          asset_content_type: application/zip
