name: Follow-up Updates

on:
  workflow_dispatch:

jobs:
  check-updates:
    name: Check for PHP and libwebp updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install yq
        run: |
          wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Set up Git
        run: |
          git config --global user.name "claude-code[bot]"
          git config --global user.email "claude-code[bot]@ideamans.com"

      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          timeout_minutes: "10"
          direct_prompt: |
            PHPとlibwebpの更新の必要があればPRを作成してください。
