name: Follow-up Updates

on:
  workflow_dispatch:

jobs:
  check-updates:
    name: Check for PHP and libwebp updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install yq
        run: |
          wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Claude CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/anthropics/claude-code/main/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check for updates and create PR
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          claude -p 'PHPとlibwebpの更新の必要があればPRを作成してください'